### ISSUE TITLE
[BUG] `MDBX_PANIC` When Opening Corrupted Database

### ISSUE THREAD

**Issue by JaffaKetchup** [isar/isar#1011]
Hi again @simc, the performance issue was resolved by buffering. Another more serious bug now:

### Information / Reproduction Steps

Create a database **on another device** and export it with the built in method. Then import it. If the app is already running, the database refuses to work correctly (fails enough checks to show as 'invalid' in my app). If the app isn't running, then this error occurs and Flutter doesn't do anything - but the app doesn't crash.

```
Unhandled Exception: IsarError: Cannot open Environment: MdbxError (-30795): MDBX_PANIC: Environment had fatal error
```

The Inspector refuses to list the database, but the other open databases appear to work correctly. I can see the database file in my Explorer.

![image](https://user-images.githubusercontent.com/58115698/209875723-2db61440-6445-4a20-a898-b656f55f7de7.png)

I'm assuming database files aren't designed to work cross platform (or even device?). Is there a way around this? Maybe exporting to JSON like the Inspector allows, then reimporting?

### Code Sample

Exported on Android device:
```dart
database.copyToFile(outputFile.absolute.path);
```

To import on a Windows device, I simply copy the file to the correct directory and add it to my registry.

### Details

 - Platform: Android (Redmi Note 10 Pro) + Windows 11
 - Flutter version: 3.0.10 (latest)
 - Isar version: 3.0.5 (latest)

---

 - [X] I searched for similar issues already
 - [X] I filled the details section with the exact device model and version
 - [X] I am able to provide a reproducible example

**Comment by JaffaKetchup** [comment]
This appears to be a very hard to reproduce issue, as I've just tried it again, and it worked without any of the weird database name.
I'll try to make a screen recording.

**Comment by JaffaKetchup** [comment]
Here's the video of me reproducing the first bug. It is reliable, but seems to only occur if I try to read directly off of the device; if I copy it to my SSD first, it imports well, as you will see.

https://user-images.githubusercontent.com/58115698/209878107-2cc97136-5e43-4ece-8721-c40578680f98.mp4

The name being messed up indicates that maybe something is happening out of your control during the file transfer?

Anyway, now I'll try to reproduce the second issue.

**Comment by simc** [comment]
Isar does not officially support moving database files to another device. There is no real reason why it shouldn't work but I never tries it, have no tests covering it and I generally recommend to use a format like json to move data between devices

**Comment by JaffaKetchup** [comment]
But shouldn't an error like this be caught? It completely breaks the app. I understand there's no official support for direct sharing, no problem with that :)
I guess the file transfer protocol (I guess MTP) is messing things up.

**Comment by JaffaKetchup** [comment]
Closing for now, but would still like to see this handled, if you get time to diagnose :)

**Comment by JaffaKetchup** [comment]
Ah, I've realised my potential mistake here! Didn't realise you could export/import to and from JSON programmatically. I'll have to look into that option: I'd be interested to know if the exported JSON is larger than the database file?

Anyway, the issue still stands as being fatal, so I'm still erring on the side that something like this should be caught. I can implement a workaround by writing a list of successful openings to a temp file on disk, and deleting it if all databases are opened successfully. I'll probably end up doing this, especially as my use case needs to be very resistant to data loss (getting stuck up a mountain and finding out your downloaded maps are gone would be rather scary :D).

If you don't mind, I'm going to re-open this, just so it's easier to find for anyone that might have the same issue (and tell them it's still current), and so it might be fixed at some point in the future. I know corruption like this is vanishingly unlikely without greater damage, but you never know what idiots (*cough *cough me) will be trying to transfer whole databases between different operating systems!

PS. Hope you had a good New Year's, all the best to you, and another thanks for all your hard work. My package should be ready for release fairly soon, in no small part thanks to the ease-of-use of this library (except for small bits like this).

PPS. Still not sure about that second part of this issue. I can open a separate one if you'd like.

**Comment by simc** [comment]
Hey! I wish you a happy new year too!

Yes, the JSON should be larger than the database.

> Anyway, the issue still stands as being fatal

You mean it crashes the app? Did you get a stacktrace?

> this should be caught

I'm not sure it's even possible to detect this issue reliably :(

**Comment by JaffaKetchup** [comment]
If you have a look at the screen recording I posted above, you can see how it pans out. If launching the app, it seems to completely kill the Flutter process, but leaves the window open and unresponsive. There's no stack trace. If the app is already open, it causes the panic error: also no trace.

**Comment by JaffaKetchup** [comment]
Maybe some sort of 'safe mode' that lists the databases that were opened successfully? In my case, this would allow detection of the faulty database (compare directory files to successfully opened databases), and it could be deleted.
Maybe if I get some time after I've finished my project I'll look into it for you, if that's something you're interested in.

**Comment by JaffaKetchup** [comment]
(Also found out that manually editing and corrupting a database causes the same launch issue, which is captured and resolved by my system that essentially follows the rules above. This means that the error might not be that rare - of course, you can't manually edit a database whilst it is open, so the panic error never appears.)

**Comment by listepo** [comment]
I think would be nice to have native(based on isar_core) backup functionality(perhaps compressed data or serealized more efficiently than json). I guess it is possible to make a plugin for isar(written on a dart).

**Comment by JaffaKetchup** [comment]
@listepo That would be nice, but I don't want to clog up the core, so I think a plugin module would be the best way to go. I was considering implementing my idea above as well as a plugin instead of putting it in the core - especially as I've never looked into the Isar source code before :D. These two features could go hand in hand.

**Comment by JaffaKetchup** [comment]
@simc Managed to get the error of the fatal launch crash! Ran without Flutter in a tiny project, and it kicks out this message:

![image](https://user-images.githubusercontent.com/58115698/211196802-03e68d0d-daca-452f-a522-08b8eb971ed3.png)

No idea if that helps, but it's given me the thought for how to detect corruption without needing a fatal crash. Open it in an isolate first. If the isolate dies unexpectedly, that database is corrupted.

**Comment by JaffaKetchup** [comment]
@simc Bad news, it is impossible to catch the error using the method I suggested above - it crashes the app and all isolates, without running the `onError` handler.

Can you say which dependency might be causing this? I'd like to raise an issue there. Or do you think raising an issue in the Dart repo would be better?

**Comment by GregoryConrad** [comment]
@JaffaKetchup That's probably because `mdbx` segfaults and causes all hell to break loose.

It really isn't an issue with any other project; you should be passing around the database contents as JSON. If you are worried about JSON size, compress it with something like `zip`.

If you really wanted to continue down this road (which you really shouldn't without a good reason), you could try to spawn a new process (i.e. C's `fork()`) and do the check in that process. I'm not sure exactly if isolates are implemented as threads or processes under the hood, but considering even the main isolate died, I am guessing that they are threads. But again, this is *not* a good way to handle checking the database file. You could also try using `mdbx` directly, but you might get the panic still.

**Comment by JaffaKetchup** [comment]
@GregoryConrad Thanks for the insight.

This issue has transformed from an issue about sharing databases to an issue that occurs when they are corrupted, so that part of the issue doesn't matter (works perfectly as long as you don't get a transfer protocol involved directly). Also want to avoid compressing JSON, it's slow and ineffective against the contents of my databases (99% blobs) + it takes a long time to export/import.

Might try your C suggestion, although I don't particularly want to add that into my package. For now, the system I described above should be acceptable.

**Comment by JaffaKetchup** [comment]
@simc, just letting you know that [FMTC](https://fmtc.jaffaketchup.dev/) v7 has been published. Thanks for all your help!

![image](https://user-images.githubusercontent.com/58115698/216780124-1e80704f-b386-47d6-a488-baf18a8422a7.png)

**Comment by simc** [comment]
This is unfortunately almost impossible to achieve. Closing.

**Comment by erthink** [comment]
As a _libmdbx_ (key-value storage engine) developer, I decided not to leave the topic unanswered and reply just in case, as the information may be useful to other users:
1. The database file can only be copied if a database is not in use, and there is complete confidence in this. Otherwise, in case direct copying a file of a currently used/opened DB you could get a corrupted / inconsistent copy. An used/opened database must be copied via the [appropriate API](https://libmdbx.dqdkfa.ru/group__c__extra.html#ga165f1beca577d07915de13d6a09e226e).
2. It is no any way nor a possibility to "import", "insert" or force-to-use an external DB file on the fly into a running process/application (i.e. an opened DB-environment). The `MDBX_PANIC` or `MDBX_CORRUPTED`errors are most likely to returned in such case.
3. The format of a DB file depends on the system endianess (aka byte order) and some specific options available only during the libmdbx build. So direct DATABASE migration is possible between many platforms, but for full versatility `mdbx_dump` + `mdbx_load` utils should be used.
4. _libmdbx_ support a "safe mode" to opening a potentially corrupted or untrusted DB, see [MDBX_VALIDATION](https://libmdbx.dqdkfa.ru/group__c__opening.html#gga9138119a904355d245777c4119534061af6ccfacef80badbb16454be9548372f3) and [mdbx_env_open_for_recovery()](https://libmdbx.dqdkfa.ru/group__chk.html#gad919724e8d6d833c75a1bd5edba32780).

**Comment by JaffaKetchup** [comment]
Thanks @erthink :)
