### ISSUE TITLE
Data in .isar file was not deleted

### ISSUE THREAD

**Issue by Cierra-Runis** [isar/isar#1043]
### Steps to Reproduce

Everything is fine but I found that the data wasn't deleted in .isar file. It seems that just make data unreadable.

### Code sample

1. delete buttom

```dart
IconButton(
  onPressed: () {
    Navigator.pop(context);
    DevTools.printLog(
      '${diaryEditorModel.diary.id!}',
    );
    isarService.deleteDiaryById(
      diaryEditorModel.diary.id!,
    );
  },
  icon: const Icon(Icons.delete),
),
```

2. isarService

```dart
Future<void> deleteDiaryById(int id) async {
  final isar = await db;

  await isar.writeTxn(() async {
    final success = await isar.diarys.delete(id);
    DevTools.printLog('deleted: $success');
  });
}
```

### Details

 - Platform: IQOO neo5
 - Flutter version: 3.3.9
 - Isar version: 3.0.5

**Comment by Jtplouffe** [comment]
This is the expected behaviour.
Most database do that, where deleting data will make it so it is no longer returned in queries, but may still be present in the underlying storage, until a compaction cycle runs.

This behaviour is used to greatly improve performance.

There a 2 ways to force a compaction in `Isar`:
- On launch, using the `compactOnLaunch` argument in `Isar.open`;
- `instance.copyToFile(...)`, which will create a compacted copy of the database file.
