### ISSUE TITLE
Add 32 incompatibility informations in documentation 

### ISSUE THREAD

**Issue by JsonLinesCode** [isar/isar#113]
**Is your feature request related to a problem? Please describe.**
I was frustrated when I discovered Isar was not compatible with 32 bits devices.

**Describe the solution you'd like**
Please  add it in the Isar limitations at least. It could spare other developers the remigration of their code when they discover it. 

**Describe alternatives you've considered**
I've seen in an issue that it was related to testing issues and would require too much work. So I don't have any alternatives.  

**Version**
 - Platform: iOS, Android

**Comment by yringler** [comment]
Yes, this was also mentioned in another issue https://github.com/isar/isar/issues/48#issuecomment-825553230 , but should be mentioned in the [docs](https://isar.dev/limitations).
@leisim , I understand your reasons for not supporting 32bit.
I do not know how many of my app users have a 32bit device; I don't know that google play console or google analytics readily supply that information. Because of the (religious) nature of my app and it's smaller (600+) user base, I'd hate to lose any users by requiring 64bit.
I know that money isn't the issue here, but still - they're are many people who would love to support this project and your work, especially considering the central, critical role of data management. Perhaps if you enabled github sponsors for this project, and would take the extra time to support 32bit if a certain number of sponsors would be found?
For example, ryanheise, who also maintains a critical package, has 24 (!) [sponsors](https://github.com/sponsors/ryanheise#sponsors). We're not talking big money here, but it's nice, and would hopefully serve to make everyone feel better about your work.

**Comment by leisim** [comment]
Hey @yringler I definitely plan to continue working on this project :+1: and I'll look into 32bit support too

**Comment by yringler** [comment]
> I definitely plan to continue working on this project :+1: 

Great!

> and I'll look into 32bit support too

Even better!

I'm actually in the middle of completely rewriting data handling in my app. It'll probably be another month or so until that's done. I'm currently in the direction of using moor (a pretty thin abstraction around sqlite) because of the 32 bit support, but with my new (hopefully) properly abstracted data handling, I'd be thrilled to swap out for  isar and see how it goes, whenever that's ready.

(For some context, currently my app accesses the hivedb boxes directly all over the place. I've loved working with hivedb, and I doubt I'll bother moving away from it for smaller things, but I'm moving to something else to store the main 10MB of app data.)

**Comment by jpolstre** [comment]
In fact, starting with this limitation would save us a few hours, I am very disappointed.

**Comment by yringler** [comment]
Opened PR to put 32 bit limitation prominently in README

**Comment by leisim** [comment]
@yringler Yes it would. It's a super cool project with a lot of improvements over lmdb.
I'm looking into switching to it before a stable release...

**Comment by leisim** [comment]
Fixed with stable release
