### ISSUE TITLE
why is the .isar db file larger than 100mb but there are only less than 100 datas.

### ISSUE THREAD

**Issue by zhangwb1996** [isar/isar#1152]
### Discussed in https://github.com/isar/isar/discussions/1151

<div type='discussions-op-text'>

<sup>Originally posted by **zhangwb1996** March 24, 2023</sup>
there were 500K test datas (it was due to not run build__runner in terminal after changing the collection )  in isar,
1. clean isar from the `Isar Inspector`,
2. restart my App again,
3. inset less than 100 datas from UI of this App.

then, i find the  .isar db file is larger than 100mb only with less than 100 datas.
<img width="476" alt="image" src="https://user-images.githubusercontent.com/41967295/227417905-5fdc7716-b90f-493f-a7b3-0a8128265d3c.png">
<img width="100" alt="image" src="https://user-images.githubusercontent.com/41967295/227417956-fc4b7acd-024a-492d-ac3e-f9082a1e8544.png">
</div>

**Comment by Jtplouffe** [comment]
As mentioned in #1151, entries deleted from the database may not be immediately deleted from the underlying file, in order to improve performance.

A way to mitigate this would be to use the `compactOnLaunch` argument from `Isar.open`, which will compact the database file (therefore removing "gaps" in the file).

Please refer to https://github.com/isar/isar/issues/1043#issuecomment-1383146114.
