### ISSUE TITLE
Fuzzy text search

### ISSUE THREAD

**Issue by yringler** [isar/isar#135]
**Is your feature request related to a problem? Please describe.**
I would like to eventually move my app to issar. One thing I'd like to do is fuzzy searching, which would allow mispellings, word gap etc, because a literal text search will always miss a ton of content. This especially applies to my app, where many "English" words are transliterations of Hebrew, and everyone types that a bit differently.

**Describe the solution you'd like**
Even a primitive search with no configurability is better than nothing! Say .where().fuzzyMatches('shumayim') matching text with 'shamayim' with a hard coded "distance" to match would be great.

**Describe alternatives you've considered**
Literal text search - faster than using online search, but poor results
Using API for text search - better results, but slower

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.5.4]
 - Isar version: [e.g. 0.5.0]

**Comment by leisim** [comment]
@yringler Do you have a reference implementation or some example of how you would want this to work? Would a fuzzy filter be enough or do you also want to use an index?

**Comment by yringler** [comment]
Nope. I saw a Wikipedia article way back with different algorithms, that's as far as my knowledge reaches.

A fuzzy filter would be enough.

This functionality doesn't exist in any other flutter db as far as I'm aware, so missing it doesn't put isar at a disadvantage. But it would be useful to have.

**Comment by om-ha** [comment]
I have evaluated dart fuzzy algorithms and used the best one that suited my use-case, but I suppose it applies to Isar too. I can share my (simple) findings and maybe help with the implementation.

**Comment by leisim** [comment]
@om-ha that would be great. We won't be limited to dart algorithms because the searching will happen natively in Isar core anyway.

**Comment by leisim** [comment]
Okay I looked into different algorithms and types of fuzzy matching and I see a few problems:

- fuzzy matching can be expensive so we likely want to use an index. That's difficult to implement for many algorithms
- there is no "perfect" algorithm. Choosing the right one highly depends on the individual use case (for example soundex vs levenshtein)
- it's not trivial to make fuzzy matching work with the existing API. For example because in contrast to other filters, the fuzzy filter should also sort the results by their rank and return the rank

What do you think?

**Comment by leisim** [comment]
@yringler I think the easiest approach would be to choose a Hebrew phonetic algorithm and store the result in an indexed field. Then you get accurate and super fast fuzzy search

**Comment by om-ha** [comment]
> * fuzzy matching can be expensive so we likely want to use an index. That's difficult to implement for many algorithms

- It's true fuzzy matching can be expensive, and there's a need for index.

> * there is no "perfect" algorithm. Choosing the right one highly depends on the individual use case (for example soundex vs levenshtein)

- From what I see `soundex` is more limited than `levenshtein`, as the former depends on the natural human language. In other words, `soundex` is limited to English. So [other variants](https://en.wikipedia.org/wiki/Soundex#Variants) have to be used for non-English words.

> * it's not trivial to make fuzzy matching work with the existing API. For example because in contrast to other filters, the fuzzy filter should also sort the results by their rank and return the rank

- I haven't looked into filters, but from what I [see here](https://github.com/isar/isar#queries), what you are saying checks out. We need complex return results.

All in all, I because `levenshtein` is more general, there are few implementations based on it that comes to mind:
1. [RapidFuzz](https://github.com/maxbachmann/RapidFuzz#benchmark), this one is superb and is even more high-performing than `TheFuzz`.
2. [TheFuzz](https://github.com/seatgeek/thefuzz) (previously [FuzzyWuzzy](https://github.com/seatgeek/fuzzywuzzy))

**Comment by om-ha** [comment]
That being said, I think your statement here is best suited for case-by-case scenario. It is very high performing but limited to the nature of how `soundex` [works](https://en.wikipedia.org/wiki/Soundex).

> @yringler I think the easiest approach would be to choose a Hebrew phonetic algorithm and store the result in an indexed field. Then you get accurate and super fast fuzzy search

**Comment by tomasweigenast** [comment]
> Okay I looked into different algorithms and types of fuzzy matching and I see a few problems:
> 
> * fuzzy matching can be expensive so we likely want to use an index. That's difficult to implement for many algorithms
> * there is no "perfect" algorithm. Choosing the right one highly depends on the individual use case (for example soundex vs levenshtein)
> * it's not trivial to make fuzzy matching work with the existing API. For example because in contrast to other filters, the fuzzy filter should also sort the results by their rank and return the rank
> 
> What do you think?

Maybe we can try a better full text search algorithm instead of only fuzzy search

**Comment by leisim** [comment]
@tomasweigenast Do you have an example? Maybe from other embedded databases 🙂

**Comment by leisim** [comment]
Closing this for now since it is not planned near term.
