### ISSUE TITLE
Performance downgrade on stream and standard where()

### ISSUE THREAD

**Issue by richard457** [isar/isar#1385]
### Steps to Reproduce
```dart

@override
  Stream<Transaction?> pendingTransactionStream() {
    int branchId = ProxyService.box.getBranchId()!;
    return db.read((isar) => isar.transactions
        .where()
        .statusEqualTo(pendingStatus)
        .and()
        .branchIdEqualTo(branchId)
        .build()
        .watch(fireImmediately: true)
        .asyncMap((event) => event.last));
  }

```
where the id from transactions collection is a string, it takes between 5~10 seconds for the query to get data and when new data is added it is the same

### Details

 - Platform: Android, Galaxy S7, x86 Android Emulator on Windows etc.
 - Flutter version: 3.10.6
 - Isar version: v4

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by simc** [comment]
I think I know what the issue is: you probably use a lot of async transactions and subscriptions. They are all executed in their own isolate and there is currently a limit of 16 isolates and 8 on older devices. There is a fix in the Dart dev builds but it's not released yet. I also applied this fix in Isar but have to wait until the next Flutter version. Then this issue will be gone.

**Comment by richard457** [comment]
cc @simc

**Comment by simc** [comment]
Yes. Use `4.0.0-dev.10` to fix the issue
