### ISSUE TITLE
[Isar v4] Missing support for Set

### ISSUE THREAD

**Issue by ilovelinux** [isar/isar#1386]
### Steps to Reproduce

See code below.

### Code sample

```dart
import 'package:isar/isar.dart';

part 'test.g.dart';

@collection
class Data {
  Data(this.id, this.otherData);

  final int id;
  final Set<OtherData> otherData;
}

@embedded
class OtherData {
  OtherData(this.id);

  final int id;
}
```

Error:

```console
[SEVERE] isar:isar_generator on lib/data/db/test.dart:

Unsupported type. Please add @embedded to the type or implement toJson() and fromJson() methods or annotate the property with @ignore let Isar to ignore it.
package:example/data/db/test.dart:10:24
   ╷
10 │   final Set<OtherData> otherData;
   │                        ^^^^^^^^^
   ╵
```

### Details

 - Platform: Mac OS X 13.4.1
 - Flutter version: 3.1.0
 - Isar version: 4.0.0-dev.9

---

 - [X] I searched for similar issues already
 - [X] I filled the details section with the exact device model and version
 - [X] I am able to provide a reproducible example

**Comment by simc** [comment]
Sets don't really make sense for the database because internally Isar only supports lists. If you prefer using sets just create a getter and setter for your model. I don't think supporting Sets is a good idea. We'd also have to support other classes for convenience like Duration or Size but I think Isar should be kept as simple as possible.
