### ISSUE TITLE
Support data type 'Duration'

### ISSUE THREAD

**Issue by Bohne13** [isar/isar#1537]
**Is your feature request related to a problem? Please describe.**
I do use DateTime as a start and end point, but what I really want to store is a duration.
At the moment I have to implement Duration by myself.

**Describe the solution you'd like**
Would be nice to have  'Duration' as Isar supported data type.

**Describe alternatives you've considered**
Didn't consider any alternatives.

**Version**
 - Platform: iOS, Android, Mac, Windows, **Linux**, Web
 - Flutter version: [3.16.5]
 - Isar version: [4.0.0-dev14]

**Comment by JulianSchmidtZollsoft** [comment]
Bringing `TypeConverters` back could also be a good compromise for all classes that can't be declared as embedded objects: https://github.com/isar/isar/issues/1493.

**Comment by oppware** [comment]
Why don't you just store an integer micro- or milliseconds?

**Comment by Cierra-Runis** [comment]
> Why don't you just store an integer micro- or milliseconds? 

Maybe he doesn't like add a `getter` more.

**Comment by Cierra-Runis** [comment]
> > Why don't you just store an integer micro- or milliseconds?
> 
> Well, that's basically what I do for now. I have a seperate class implementing 'duration' with two integers for hours and minutes.
> 
> But why implementing it by myself, if there is already a build in 'Duration' class in Dart?
> 
> I thought maybe I'm not the only one who tries to deal with durations in a database.

```dart
const Duration(
    {int days = 0,
    int hours = 0,
    int minutes = 0,
    int seconds = 0,
    int milliseconds = 0,
    int microseconds = 0})
    : this._microseconds(microseconds +
          microsecondsPerMillisecond * milliseconds +
          microsecondsPerSecond * seconds +
          microsecondsPerMinute * minutes +
          microsecondsPerHour * hours +
          microsecondsPerDay * days);
```

Before isar support it, just storing `microseconds`, you don't need to create a class with hours and minutes, then add a getter to you isar data class.

**Comment by oppware** [comment]
> > Why don't you just store an integer micro- or milliseconds?
> 
> Well, that's basically what I do for now. I have a seperate class implementing 'duration' with two integers for hours and minutes.
> 
> But why implementing it by myself, if there is already a build in 'Duration' class in Dart?
> 
> I thought maybe I'm not the only one who tries to deal with durations in a database.

All Duration is, is one integer, with a few getters, that's it.
That one integer is microseconds and every database saving this type is saving only that one integer microseconds.
The getters are as follow
- milliseconds = micro / 1000
- seconds = micro / 1000000 (1000X1000)
- minutes = micro / 160000000 (60x1000x1000)
- hours = micro / 13,600,000,000 (60x60x1000x1000)
- days ...
- and so on

I hope you get the point.
So if you don't need a finer resolution than minutes, you can just save one integer "minutes" and when you read the minutes valuer from the database you could do
final int durationInMinutes = 90; // value read from database
final myDuration = Duration(minutes: durationInMinutes);
print(myDuration); // 1:30:00.000

If you store a lot of data your database would blow up quickly by storing an unnecessary class instead of just one integer value.

I hope that helps.

**Comment by Bohne13** [comment]
Thanks, 
I haven't thought about that, so I will change my code to only store minutes and a function or a getter to translate it into hours and minutes!

**Comment by Dassderdie** [comment]
> Why don't you just store an integer micro- or milliseconds?

You would have to create a getter as well as an additional constructor that accepts a duration and converts it to milliseconds. IMHO is this a workaround but not a nice solution. From an outsiders perspective it would be confusing why such a class has two constructors.

**Comment by Dassderdie** [comment]
> Why don't you just store an integer micro- or milliseconds?

You would have to create a getter as well as an additional constructor that accepts a duration and converts it to milliseconds. IMHO is this a workaround but not a nice solution. From an outsiders perspective it would be confusing why such a class has two constructors.

**Comment by Dassderdie** [comment]
> Not sure what you mean by you would need two constructors?
> You can have you int minutes field in your class which the class stores the value for and then another field of type Duration annotated @ignore and in the contructor of the class you do myDuration = Duration(minutes: durationInMinutes)
> whereby durationInMinutes is the field stored in isar db
> It's using one constructor and you never have to worry about it.
> 
> Correct me if i misunderstood something


My thoughts were you need one constructor for Isar to create an object from the internal database values. It would have `int durationInMinutes` as an argument. This constructor should only be used by Isar as outside classes shouldn't be aware of the implementation detail that Duration is stored as an int in the isar database.

The second constructor should be used from the outside world and has `Duration duration`. It would convert `Duration` to `int` to save it in Isar.

If I understand you correctly, you would only expose one constructor that accepts Duration as an int. While this works, I don't really like it as a consumer of my API would have to do the conversion from Duration to int by himself.

**Comment by oppware** [comment]
As far as i know Isar can only constructors without required argument...
so only one constructor but in the body you fill the Duration class
and in your setter "e.g. setDuration" you fill your integer with duration.inMinutes
Nobody will see from the outside/api what you do internally.

**Comment by Naam** [comment]
If it's "just" an integer with a few getter, the support should be easy to add and lower the friction Isar has when integrating it to a codebase.
While the workarounds are nice to have, the concerns remain.
`Duration` and `DateTime` are very similar, and `DateTime` is supported.

I am unfamiliar with the build & testing process, but looking at the code, I was able to put together this pull request as I've just hit this limitation today and found out about this open issue. Hopefully, someone can chime in and test & comment so it can be merged back. I've targeted 3.1.0 because that's what is in "production" and most people are using now. I guess it can be ported to 4.0 too, at a first glance the code looks identical on the modified areas.
