### ISSUE TITLE
Query by List of index-entries

### ISSUE THREAD

**Issue by mikes222** [isar/isar#1634]
**Is your feature request related to a problem? Please describe.**
I have performance problems when I want to retrieve multiple - up to 500 - entries from database by an index.

**Describe the solution you'd like**
I would like to have an API for the buildQuery() clause something like:

    _isar!.collection<T>().buildQuery(
        whereClauses: [
          IndexWhereClause.**AllOf**(
            indexName: r'serverId',
            values: **List<IndexKey> keys**,
          ),
        ],
      )

**Describe alternatives you've considered**

Currently I retrieve the items via a loop like so:

    List<T> result = [];
    for (String key in keys) {
      T? res = await _isar!.collection<T>().buildQuery(
        whereClauses: [
          IndexWhereClause.equalTo(
            indexName: r'serverId',
            value: [key],
          ),
        ],
      ).findFirst();
      if (res != null) result.add(res);
    }
    return result;

**Version**
 - Platform: Android
 - Flutter version: 3.22.2
 - Isar version: 3.1.0+1

**Comment by Jtplouffe** [comment]
You should be able to do something like this:

```dart
final results = await isar
    .myCollection
    .where().anyOf(keys, (query, key) => query.keyEqualTo(key))
    .findAll();
```

Or, iirc, you can pass multiple `IndexWhereClause` to the `whereClauses`, and it should perform an `or` between them all.

If you want even more performance, you might want to consider finding a better index that could group all of your objects together, or, depending on the size of the collection, it might even be faster to just do a regular non-indexed search instead of having to lookup many indexes.

**Comment by mikes222** [comment]
thank you for the quick reply. I create a list of ``IndexWhereClause`` and it is so much faster now!

    List<IndexWhereClause> clauses = keys
        .map((key) => IndexWhereClause.equalTo(indexName: r'serverId', value: [key]))
        .toList();
    List<T> result = await _isar!
        .collection<T>()
        .buildQuery<T>(
          whereClauses: clauses,
        )
        .findAll();
