### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by dgandhi17** [isar/isar#22]
You might wanna to look at this link for the benchmarks of existing flutter/dart database against Isar version.

https://objectbox.io/objectbox-dart-flutter-v0-11-database-performance-relations/

**Comment by enzotar** [comment]
In addition to benchmarks, it would be interesting to see the differences between Objectbox and Isar.

**Comment by iapicca** [comment]
[objectbox](https://pub.dev/packages/objectbox) (that seems to have [confirmed](https://github.com/objectbox/objectbox-dart/issues/244#issuecomment-843453458) its claim of [hive being deprecated](https://user-images.githubusercontent.com/45637986/118714729-66a31380-b82b-11eb-8793-9dcbb8e61a26.png)) has publish a benchmark against [hive](https://pub.dev/packages/hive)
nevertheless its more similar to [isar](https://pub.dev/packages/isar), for `query` and `lack of web support`
as there was already a [request for benchmark](https://github.com/hivedb/hive/issues/246#issuecomment-778755774) it would be interesting to compare `objectbox` to `isar` using their [benchmark](https://github.com/iapicca/objectbox-dart-performance)

**Comment by vaind** [comment]
Hey, since there were some community requests (and contributions) towards adding Isar to the objectbox-dart-performance benchmark app, we're going to [merge the PR](https://github.com/objectbox/objectbox-dart-performance/pull/3) soon even though there are some features missing/not working properly yet, to give some preliminary comparison. If any of you guys would like to have a look/review/contribute, please do so.

**Comment by leisim** [comment]
Here are some benchmarks that I plan to extend in the future: https://github.com/isar/isar_benchmark
