### ISSUE TITLE
Support multiple instances with different schemas

### ISSUE THREAD

**Issue by FredJul** [isar/isar#297]
**Is your feature request related to a problem? Please describe.**
Isar allows to instanciate several Isar objects, but they need to have the same schemas. I'm currently developing a big professional app and would like to have one global database with global data and one per user with user's data, so that I am sure I cannot accidently read/delete others user data (the device can be use by several people and they can login with a different account on the same device).

**Describe the solution you'd like**
I would like to be able to define different schemas for each instance.

**Describe alternatives you've considered**
Currently I need to put all my schemas in all isar instances, even if I'm not using all schemas for a specific instance.

**Version**
 - Platform: iOS, Android, Mac, Windows
 - Flutter version: 2.10.3
 - Isar version: 2.2.1

**Comment by richard457** [comment]
In the https://github.com/isar/isar/issues/2 feature, I suggested having channels as a way to grant access to some user data, this way you can not have access to data in the first place if you are not granted access to it.

**Comment by FredJul** [comment]
@richard457 that seems powerful but quite complex, and I doubt this will be even possible until https://github.com/erthink/libmdbx supports something similar.

I believe my proposal to be much simpler and doable in Isar itself.

**Comment by leisim** [comment]
I thought about this but ultimately decided not to implement it because additional collections do not bring any overhead and it is very complicated and error prone to implement / use multiple instances with different schemas.

Why do you think it would be beneficial to your app? Maybe you have some ideas I didn't consider :)

**Comment by FredJul** [comment]
@leisim well as I said having multiple DB file allows me to:
- separate some data and be sure I can't mix them (in my case I don't want to be able to read data from another user, so I have one global db with few configuration/login data and one db per user with user's data)
- simplify the queries (no need to filter all data to be sure they are part of the correct user)
- big apps may want to have several modules with a specific db per module (not my case but still possible)
- maybe being more resilient to file corruption (one user db can be broken, but it will not affect the other users)

Today I can have this but I need to provide all schemas to all isar instances. I see two main advantages to allow different schemas:
- the dev does have not an strange error when he tries to do it, and does not have to put the schemas list in common.
- the dev will have an error if he tries to read some data in the wrong isar (like when you forget to declare some schemas), with my workaround he simply receives empty data and may have difficulties to understand the issue.

For your information, objectbox does not have such limitations and allows multiple DBs with different schemas.

**Comment by leisim** [comment]
Unfortunately this would require major changes to Isar's API to make it work and then it would still be possible to make a mistake and incorrectly use a collection on an unsupported instance. I still don't see a clear advantage on not having some collections in an instance. They do not use any space if you don't store anything in them.

I'm going to close this for now because I don't think it's a good fit for Isar.

> separate some data and be sure I can't mix them

I suggest to create a little logic on top of the Isar interface to perform custom verification

> simplify the queries

I don't really see how multiple instances simplify queries. You can do the same with multiple collections.

> big apps may want to have several modules with a specific db per module

That's a good point but Isar supports multi package configurations. Each package can define their own collections.

> maybe being more resilient to file corruption

We should aim for a corruption free database either way 😅

**Comment by leisim** [comment]
@tr-stan It's the second one. The entire app needs to use the same schema.
