### ISSUE TITLE
Embedded inspector

### ISSUE THREAD

**Issue by aloisdeniel** [isar/isar#476]
Since the inspector is developed with Flutter, it would be awesome to offer a way to embed it inside the app itself (_as a debugging tool_)! This would also avoid the communication setup which is sometimes failing because of network.

For example, by referencing the `isar_inspector` package with an `openIsarInspector` method : 

```dart
await context.openIsarInspector([PostSchema]);
```

This would imply : 
* implementing an alternative local communication channel implementation (_instead of websocket only_)
* fully responsive screens for opening it from mobile apps

**Comment by leisim** [comment]
I love the idea. You don't always have a device to connect to and having it in the app could be super handy.

**Comment by Viper-Bit** [comment]
what's the point, I don't get it. inspector just works in debug mode and when u debugging your app definitely u have another device, maybe we can just use launchUrl to open inspector from app.
```dart
static Future<void> openInspector() async {
    if (!await launchUrl(_inspectorUrl)) throw 'Could not launch $_inspectorUrl';
}

await Isar.openInspector();
```
if we want to use inspector in release mode that is another thing.
instead of embedding inspector into each app i think its better to create a universal inspector that can works with db files and in future with server (when sync implemented)

**Comment by aloisdeniel** [comment]
My idea was initially to embed it with each app, even in release mode eventually.

The server connection would be ideal too but only if you don't have to host it by yourself. So it would imply offering such a service and an associated business model.
