### ISSUE TITLE
Adding stats to inspector

### ISSUE THREAD

**Issue by aloisdeniel** [isar/isar#479]
Having stats data from the inspector would be super useful for analyzing usage.

 The more obvious one are the collection sizes on disk, but a realtime mode could eventually be added to observe the number of read/write operation happen.

**Comment by leisim** [comment]
Great idea. The new web based inspector of 3.0.x versions already displays collection size including indexes and number of objects in each collection in real time.

Since Isar uses virtual memory, the actual disk access is managed by the kernel. Instead we could show ongoing read and write transactions.

**Comment by simc** [comment]
This is implemented in v4
