### ISSUE TITLE
Incorrect Path Resolved When Downloading Isar Binaries

### ISSUE THREAD

**Issue by scottbisaillon** [isar/isar#513]
**Steps to Reproduce**
Calling `Isar.initializeIsarCore` in a unit test on Windows without specifying the library paths results in the binary being downloaded at the root of the drive.

In `isar_core.dart#_getLibraryDownloadPath` ,
```dart
final dirSegments = Platform.script.path.split(Platform.pathSeparator);
```
results in `/C:/Users/<USER>/AppData/Local/Temp/dart_test.c7eab765/test.dart_1.dill`.

Since this is just a single element list, the following: 
```dart
      final dir = dirSegments
          .sublist(0, dirSegments.length - 1)
          .join(Platform.pathSeparator);
```

results in just an empty string/path.

**Code sample**
```dart
await Isar.initializeIsarCore(
      download: true,
    );
```

**Version**
 - Platform: Windows
 - Isar version: 3.0.0-dev.8

**Comment by scottbisaillon** [comment]
I am going to close this since I think the issue is related to how Android Studio executes the unit tests. When running them from the command line, I seem to get the correct results.

**Comment by leisim** [comment]
Oh that's interesting thanks for investigating. Nothing we need to fix then 🥳

**Comment by Moseco** [comment]
@leisim I think this is still a problem on Windows when running from terminal or VS Code directly (I have tested on MacOS and it works as expected).

Similar to the author of the issue, this ```Platform.script.path.split(Platform.pathSeparator);``` results in ```[/C:/Users/<USER>/path/to/project/main.dart]```

This then causes the final directory to be set to an empty string and isar attempts to download to root.

I think the problem comes from split using ```Platform.pathSeparator``` which is ```\``` on Windows, but the path returned by ```Platform.script.path``` uses ```/```. So maybe split should always use ```/``` or do some other check to see what separator is present.

Version

- Platform: Windows
- Isar version: 3.0.0-dev.8
- Flutter version: 3.0.5
