### ISSUE TITLE
Enums and Isar

### ISSUE THREAD

**Issue by Mihai-B** [isar/isar#583]
**Is your feature request related to a problem? Please describe.**
Hi. First, I want to say that I am using Isar for some time and I really love it. This is going to become one of the best packages there is on pub.dev for data store.

I do want to say that with update 3.0.0-dev.10 there is a "modification" on how Isar handles the Enums and I think the new way is not correct.
So basically, when you have an Enum that you want to store, you need to extend that enum "with IsarEnum<String>". I think this new way of doing it is not as good as it was before because now you have to add Isar dependencies everywhere in your code.

**Describe the solution you'd like**
The old way of doing it was much better even if it was a bit more boilerplate code.
```
class BuildingStatusConverter extends TypeConverter<BuildingStatus , int>
```
The advantage of using this method is that you can create an type converter for that enum that is located along side your entity class.
There are situation where you want to store an Enum that is not necessarily in your repository. Adding repository dependencies everywhere in your code can become problematic and **sometimes those enums are not even in your code**.

I do hope this is taken in consideration and we switch back to old way of doing it.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Isar version: 3.0.0-dev.10

**Comment by leisim** [comment]
The problem with `TypeConverter`s is that it is quite difficult for users to get them right. It is easy to accidentally break existing models. Also `TypeConverter` give too much freedom and lead to weird edge cases with queries.

To your point about Enums in repositories: I don't think it is a problem to have Isar dependencies outside of repositories (for example for listening to updates in widgets) but you can just use dedicated enums for Isar or do something like this:

```dart
enum YourEnum {
  a, b, c
}

@collection
class YourModel {
  YourModel(this.id, this.yourEnumIndex);
  
  Id id;
  
  byte yourEnumIndex;
  
  YourEnum yourEnum => YourEnum.values[yourEnumIndex];
}
```

I would argue that even this code is cleaner and easier to maintain than `TypeConverter`s.

You generally should not store enums that you do not own because they might change in the future in a way that is not backwards compatible.

**Comment by Mihai-B** [comment]
The case with enum from libraries is for situations where there are multiple applications that have a "core" library. All the libraries are owned by the same user/company, but now, instead of having a core library with models that are generally used to communicate between apps or with the API, now you have to contain also a database dependency OR make new wrappers or new enums in that specific application.
What I am trying to say is that with this new approach you win some you lose some, but I still think the scale is more on the lose some.

**Comment by Mihai-B** [comment]
Maybe an anotation is more simple like:

```
enum YourEnum {
  a, b, c
}

@collection
class YourModel {
  Id id;
 @Enumerated(EnumType.STRING)
  YourEnum yourEnum
}
```
Isn't something like this a bit more clean ?

**Comment by leisim** [comment]
I like this suggestion very much! The only problem I have is that it does not allow custom database values. It is not recommended to use enum name or index for the database because that will require you to never rename or reorder your enums.

How about something like this:
```dart
enum YourEnum {
  a, b, c;
  
  byte get value => {
    switch(this) {
      case a:
        return 0;
      case b:
        return 5;
      case c:
        return 20;
    }
  }
}

@collection
class YourModel {
  Id id;
  
  @Enumerated('index')
  YourEnum? enumWithIndex;
  
  @Enumerated('name')
  YourEnum? enumWithName;
  
  @Enumerated('value')
  YourEnum? enumWithValue;
}
```

**Comment by Mihai-B** [comment]
That can also looks very nice.
Just an alternative if you think it looks better:
```
 @Enumerated(EnumType.ORDINAL) // or EnumType.INDEX
  YourEnum? enumWithIndex;
  
 @Enumerated // this uses the index by default
  YourEnum? enumWithIndex2;
  
  @Enumerated(EnumType.STRING) // or  EnumType.NAME
  YourEnum? enumWithName;
  
  @Enumerated(EnumType.Method, "value")
  YourEnum? enumWithValue;
```

**Comment by leisim** [comment]
Or this:

```dart
@collection
class YourModel {
  Id id;
  
  @enumOrdinal
  YourEnum? enumWithIndex;
  
  @enumName
  YourEnum? enumWithName;
  
  @EnumProperty('value')
  YourEnum? enumWithValue;
}
```

So many choices 😲

**Comment by fix92** [comment]
related question on this. Will it be possible to update from the previous TypeConverter (if used with enums) to the new IsarEnum? Or if no, is there a migration guide that can be applied? Because when trying to migrate from 2.5.0 to 3.0.0-dev.10 I'm getting a `"IsarError: SchemaError: Could not deserialize schema JSON"`. Back when I tried this with " 3.0.0-dev.8" it worked though, so thinking it's the enum that's the problem here.
However if this should already migrate smoothly, maybe there's some more verbose output feature that I can dig around?

**Comment by leisim** [comment]
@fix92 could you please share the collection class that causes the issue

**Comment by Mihai-B** [comment]
@leisim all(last 3 proposals) look good in my opinion. it's just a matter of preferences.

**Comment by micodev** [comment]
> Or this:
> 
> ```dart
> @collection
> class YourModel {
>   Id id;
>   
>   @enumOrdinal
>   YourEnum? enumWithIndex;
>   
>   @enumName
>   YourEnum? enumWithName;
>   
>   @EnumProperty('value')
>   YourEnum? enumWithValue;
> }
> ```
> 
> So many choices 😲

😍😍 this one lit.

**Comment by leisim** [comment]
Implemented in `3.0.0-dev.11`

**Comment by fix92** [comment]
> @fix92 could you please share the collection class that causes the issue

sorry for the delay. Here a reduced example. Inside the Collection I removed redundant columns, a factory constructor and a toString override.


<details>
  <summary>Before (2.5.2)</summary>

```
@Collection()
class TheClass {
  @Id()
  int? id;

  @Index()
  late String type;

  @PhaseEnumConverter()
  late Phase phase;

  @PhaseSubTypeEnumConverter()
  @Name("sub_type")
  late PhaseSubType subType;

  TheClass(
      {this.id,
      required this.type,
      required this.phase,
      required this.subType});
}

enum Phase {
  phase_one(1),
  phase_two(2);

  const Phase(this.phaseNumber);

  final num phaseNumber;
}

enum PhaseSubType { start, end, none }

class PhaseEnumConverter extends TypeConverter<Phase, String> {
  const PhaseEnumConverter();

  @override
  Phase fromIsar(String object) {
    return Phase.values.byName(object);
  }

  @override
  String toIsar(Phase object) {
    return object.name;
  }
}

class PhaseSubTypeEnumConverter extends TypeConverter<PhaseSubType, String> {
  const PhaseSubTypeEnumConverter();

  @override
  PhaseSubType fromIsar(String object) {
    return PhaseSubType.values.byName(object);
  }

  @override
  String toIsar(PhaseSubType object) {
    return object.name;
  }
}

```
</details>

and

<details>
  <summary>After (3.0.0 dev10)</summary>

```
@Collection()
class TheClass {
  Id id = Isar.autoIncrement;

  @Index()
  late String type;

  late Phase phase;

  @Name("sub_type")
  late PhaseSubType subType;

  TheClass(
      {required this.type,
      required this.phase,
      required this.subType});
}


enum Phase with IsarEnum<String> {
  phase_one(1),
  phase_two(2);

  const Phase(this.phaseNumber);

  final num phaseNumber;

  @override
  String get value => name;
}

enum PhaseSubType with IsarEnum<String> {
  start,
  end,
  none;

  @override
  String get value => name;
}

```
</details>

didn't check the changes yet for dev11 or 12 because of:
`pub get failed (1; Because ... depends on isar_flutter_libs 3.0.0-dev.12 which doesn't match any versions, version solving failed.)`
when running flutter pub get

**Comment by fakalit** [comment]
Here's a use case where extending IsarEnum or using TypeConverters covered, but @Enumerated annotation approach doesn't seem to:

```
@collection
class YourModel {

  Id id;
  
  @Enumerated 
  List<YourEnum>? aCollectionOfEnums;

}

```

Or can we trust the Enumerated annotation to recognize that it's being used on a list @leisim @Mihai-B ?

**Comment by leisim** [comment]
@fakalit yeah lists of enums are supported already
