### ISSUE TITLE
TypeConverter not found on Prerelease: 3.0.0-dev.13

### ISSUE THREAD

**Issue by vothvovo** [isar/isar#601]
The TypeConverter class is not found. The package import is marked as unused.

**Steps to Reproduce**
Copy and paste the code from the docs into its own file: https://isar.dev/type_converters.html#creating-a-typeconverter

**Code sample**
``` dart
import 'package:isar/isar.dart';

enum Relationship {
  single,
  married,
  itIsComplicated,
}

class RelationshipConverter extends TypeConverter<Relationship, int> {
  const RelationshipConverter(); // Converters need to have an empty const constructor

  @override
  Relationship fromIsar(int relationshipIndex) {
    return Relationship.values[relationshipIndex];
  }

  @override
  int toIsar(Relationship relationship) {
    return relationship.index;
  }
}

```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 1.0.0+1 (sdk: ">=2.17.6 <3.0.0")
 - Isar version: 3.0.0-dev.13
 - Isar Generator version: 3.0.0-dev.13

**Comment by leisim** [comment]
`TypeConverters` have been removed in v3 dev versions. They have been replaced by embedded objects and enum support. The docs will be updated as soon as a stable version is available.

**Comment by SimonHausdorf** [comment]
@leisim can you give an example on how to use it now?

**Comment by muddassar-lab** [comment]
@enumerated
  late BallType ballType;
Use it like that. With @enumerated tag on tap.

**Comment by FERNman** [comment]
@leisim Since this is my first comment on this repository, I'd like to thank you for the amazing work on Isar!

However, I'm not entirely sure if it's a smart decision to remove type converters entirely. To me, it seems like there are many potential use-cases for them.

For example, I'm currently storing `Durations` by converting them to milliseconds (the possible gain in precision by using microseconds is not relevant for me). Depending on the project, needs might vary though, so being able to create my own type converter and specify the precision myself is quite handy.

I know that it's possible to circumvent this either by using the getter-setter pattern suggested in #594, or by subclassing `Duration`. Both solutions seem a little unconventional to me. Adding a getter and setter to each entity just for the database representation will clutter the codebase and creating subclasse could be confusing to new team members and works quite differently from any other database solution I've ever used (see [EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations), [Spring Data](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo-template.type-mapping), [Mongoose](https://mongoosejs.com/docs/tutorials/custom-casting.html) and [MikroORM](https://mikro-orm.io/docs/custom-types)).

What was the reason to remove this functionality? I really liked the way it was implemented before! 🙂
