### ISSUE TITLE
Failed to lookup symbol (dlsym(RTLD_DEFAU isar_connect_dart_api):

### ISSUE THREAD

**Issue by hsato-futasaji** [isar/isar#76]
**Steps to Reproduce**
1. Release build in Xcode
2. Exception occurs when app starts

<img width="859" alt="Screen Shot 2021-04-20 at 10 24 07" src="https://user-images.githubusercontent.com/76480180/115339049-ffb81d80-a1de-11eb-9927-af74019f5cd3.png">

**Version**
 - Platform: iOS
 - Flutter version: 2.1.0-12.2.pre
 - Isar version: 0.4.0
 - Isar Generator version: 0.4.0

**Comment by jhoogstraat** [comment]
I am getting the same error, but just in release mode.

**Comment by frestoinc** [comment]
> I am getting the same error. I wanted to point out that this issue does not exist in debug mode!

same here.

**Comment by kulture-rob-snider** [comment]
@leisim I believe this is the issue:
https://flutter.dev/docs/development/platform-integration/c-interop#ios-symbols-stripped

**Comment by om-ha** [comment]
## Summary
In release mode this issue is reproducible.

In debug mode this issue is not reproducible.

## Reproduction
To reproduce this in Release mode without having to release the app via Apple's TestFlight, but rather directly from Xcode:
1. Edit your current Xcode scheme within Xcode, and set `Build Configuration` to `Release` (TestFlight/AppStore) or `Profile` (AdHoc). A screenshot of this view is [found here](https://i.stack.imgur.com/wieUA.png). A more detailed explanation of this step is [found here](https://stackoverflow.com/a/14461589/10830091).
2. Run the project from Xcode to install the app (make sure it's a fresh install)
3. A white page would show on the device, that's fine. Xcode can't normally run and debug a release-mode app.
4. Kill the app and open it again.
5. Isar would not work :|

## Debugging
I know it's hard to debug a release-mode app, but it's possible achieve some debugging by either one of the following methods:
- A. After installing the release-mode app. Open the console log of the app from Xcode, here's how to do that. 
    - Within `Devices and Simulators` window. (⇧⌘2)
    - `Open Console` button
    - Choose your device from the devices list
    - From the search icon at the top right, filter by process and mention `Runner` or any other filter you think fits best. You can use multiple filters here.
- B. You can try turning off optimization for release, please find [this answer as a guide](https://stackoverflow.com/a/14473372/10830091) and the screenshot below at the bottom of this comment on what to change for optimization level. Do take care to change all optimization level options, in other words there's an optimization level for swift not mentioned in the answer but available in the screenshot. And with this, maybe it's possible to run AND debug a release-mode app from within Xcode, just like how you'd debug a debug-mode app. Note with this approach that there's a check for debugging the app, [found in this screenshot](https://i.stack.imgur.com/wieUA.png).
- C. Write your logs to a file and read them back later.

![xcode_release_optimization](https://user-images.githubusercontent.com/30494124/146639257-3501bb11-e739-4d08-8526-de1cbcbf4e8a.png)

**Comment by leisim** [comment]
Fixed now
